### ISSUE TITLE
rnn报错

### ISSUE THREAD

**Issue by Aleczhang13** [pangolulu/exact-k-recommendation#2]
Traceback (most recent call last):
  File "/hdd/xx/topk/train.py", line 24, in <module>
    g = Generator(is_training=True)
  File "/hdd/xx/topk/model.py", line 121, in __init__
    mode="BEAMSEARCH", reuse=True, beam_size=hp.beam_size)
  File "/hdd/x/topk/layers.py", line 344, in ptn_rnn_decoder
    for ik in range(beam_size)])
  File "/hdd/x/topk/layers.py", line 344, in <listcomp>
    for ik in range(beam_size)])
  File "/hdd/x/topk/layers.py", line 210, in call_cell
    cell_output, new_state = cell(_input, state)
  File "/home/x/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 385, in __call__
    self, inputs, state, scope=scope, *args, **kwargs)
  File "/home/xx/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/home/x/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 644, in __call__
    exception_str + '\n"""')
TypeError: You are attempting to use Python control flow in a layer that was not declared to be dynamic. Pass `dynamic=True` to the class constructor.
Encountered error:

**Comment by NancoChow** [comment]
你好，冒昧打扰！我最近也在看Exact-K Recommendation via Maximal Clique Optimization这篇文章，看到你之前在复现这篇文章，希望可以加个微信（18824764677）沟通一下，多谢！
