### ISSUE TITLE
Bug in the layer's file

### ISSUE THREAD

**Issue by SouravPal1995** [pangolulu/exact-k-recommendation#3]
I am currently exploring your repository in order to implement the exact k recommendation system, As I was trying to run the training.py file I ran across this bug that I am unable to fix, i.e., 
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/ec2-user/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/ec2-user/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/ec2-user/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 322, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/ec2-user/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 136, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/ec2-user/.vscode-server/extensions/ms-python.python-2022.20.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "train.py", line 26, in <module>
    g = Generator(is_training=True)
  File "/home/ec2-user/Sourav_Pal/exact-k-recommendation/model.py", line 121, in __init__
    mode="BEAMSEARCH", reuse=True, beam_size=hp.beam_size)
  File "/home/ec2-user/Sourav_Pal/exact-k-recommendation/layers.py", line 347, in ptn_rnn_decoder
    beam_sample(accum_logits, logits, point_mask, state, output_idxs)
  File "/home/ec2-user/Sourav_Pal/exact-k-recommendation/layers.py", line 325, in beam_sample
    pre_output_idxs = beam_select(pre_output_idxs, last_beam_id)
  File "/home/ec2-user/Sourav_Pal/exact-k-recommendation/layers.py", line 310, in beam_select
    for output_ta_flat in zip(*outputs_ta_flat)]
  File "/home/ec2-user/Sourav_Pal/exact-k-recommendation/layers.py", line 310, in <listcomp>
    for output_ta_flat in zip(*outputs_ta_flat)]
TypeError: 'map' object is not subscriptable
```
I know the location of the error, but I am unable to fix it. Also if possible please mention the dependencies of the code.

**Comment by Chuan1997** [comment]
You can rewrite the code as:
for output_ta_flat in zip(*outputs_ta_flat):
     outputs_l = nest.pack_sequence_as(inputs_l[0], output_ta_flat)
